# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/delicious-nbdev',
                'doc_host': 'https://galopyz.github.io',
                'git_url': 'https://github.com/galopyz/delicious-nbdev',
                'lib_path': 'delicious_nbdev'},
  'syms': { 'delicious_nbdev.Sandwich': { 'delicious_nbdev.Sandwich.slice_bread': ( 'sandwich.html#slice_bread',
                                                                                    'delicious_nbdev/Sandwich.py')}}}