# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/delicious-nbdev',
                'doc_host': 'https://galopyz.github.io',
                'git_url': 'https://github.com/galopyz/delicious-nbdev',
                'lib_path': 'delicious_nbdev'},
  'syms': {'delicious_nbdev.core': {'delicious_nbdev.core.foo': ('core.html#foo', 'delicious_nbdev/core.py')}}}