# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/blog/posts/2022-11-09-alien-vs.-ghost-pt2/index.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'inf', 'classify_images']

# %% ../nbs/blog/posts/2022-11-09-alien-vs.-ghost-pt2/index.ipynb 4
from fastai.vision.all import *
import gradio as gr

# %% ../nbs/blog/posts/2022-11-09-alien-vs.-ghost-pt2/index.ipynb 5
learn = load_learner('alien_vs_ghost.pkl')

# %% ../nbs/blog/posts/2022-11-09-alien-vs.-ghost-pt2/index.ipynb 10
categories = learn.dls.vocab
def classify_images(img):
    pred, pred_idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% ../nbs/blog/posts/2022-11-09-alien-vs.-ghost-pt2/index.ipynb 13
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['alien1.jpeg', 'alien2.jpeg', 'ghost1.jpeg', 'ghost2.jpeg', 'dunno1.jpeg', 'dunno2.jpeg']

inf = gr.Interface(fn=classify_images, inputs=image, outputs=label, examples=examples)
inf.launch(inline=False)
