# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_sandwich.ipynb.

# %% auto 0
__all__ = ['slice_bread']

# %% ../nbs/00_sandwich.ipynb 5
def slice_bread(number):
    "Slice `number` of bread."
    return f'{number} slices of bread.'
