project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        href: index.ipynb
      - text: "Blog"
        href: blog/index.qmd
    right:
      - icon: github
        href: "https://github.com/galopyz/delicious-nbdev"
  sidebar:
    style: "docked"
    contents:
      - auto: "/*.ipynb"
      - section: "Playground"
        contents:
          - index.ipynb
          - 00_sandwich.ipynb
      - section: "Blog"
        contents:
          - blog/posts/2025-01-17-how_to_solve_it/index.ipynb
          - blog/posts/2024-01-16-Resnet_part2/index.ipynb
          - blog/posts/2024-01-13-MiniAI_utilities/index.ipynb
          - blog/posts/2023-12-04-Resnet/index.ipynb
          - blog/posts/2023-11-17-Scheduler/index.ipynb
          - blog/posts/2023-11-06-Optimizer/index.ipynb
          - blog/posts/2023-10-19-Initialization_part_2/index.ipynb
          - blog/posts/2023-10-10-Initialization_part_1/index.ipynb
          - blog/posts/2023-09-26-Pytorch_Hooks/index.ipynb
          - blog/posts/2023-09-23-Convolutions/index.ipynb
          - blog/posts/2023-09-09-Learner_part_2/index.ipynb
          - blog/posts/2023-08-30-Learner_part_1/index.ipynb
          - blog/posts/2023-08-25-Callbacks/index.ipynb
          - blog/posts/2023-07-08-Hugging-Face-Features/index.ipynb
          - blog/posts/2023-03-05-Fruit_Multi_pt2/index.ipynb
          - blog/posts/2023-03-05-Fruit_Multi_pt1/index.ipynb
          - blog/posts/2023-02-25-MNIST_NN/index.ipynb
          - blog/posts/2023-02-20-MNIST_base/index.ipynb
          - blog/posts/2023-02-19-MNIST_FastAI/index.ipynb
          - blog/posts/2022-12-07-saving_jupyter_config/index.ipynb
          - blog/posts/2022-12-06-paddy1/index.ipynb
          - blog/posts/2022-12-03-live_coding7/index.ipynb
          - blog/posts/2022-11-30-live_coding6/index.ipynb
          - blog/posts/2022-11-27-live_coding5/index.ipynb
          - blog/posts/2022-11-16-live_coding4/index.ipynb
          - blog/posts/2022-11-15-live_coding3/index.ipynb
          - blog/posts/2022-11-14-live_coding2/index.ipynb
          - blog/posts/2022-11-12-live_coding1/index.ipynb
          - blog/posts/2022-11-11-alien-vs.-ghost-pt2/index.ipynb
          - blog/posts/2022-11-07-alien-vs.-ghost-pt1/index.ipynb

metadata-files: [nbdev.yml]
